id: P009399
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5345
  title: རྫོགས་པ་ཆེན་པོ་སྙིང་ཐིག་ཡ་བཞི་ལས་མཁའ་འགྲོ་ཡང་ཏིག་གི་ཆོས་སྐོར།
  author: ''
  volumes:
    c1daa22dc552471a825678fa9725094a:
      image_group_id: I3CN5347
      title: ''
      volume_number: 1
      total_pages: 620
      base_file: v001.txt
