id: I4D7E2E9C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T11:55:55+00:00'
last_modified: '2022-06-08T10:44:14.673139+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5345
  title: རྫོགས་པ་ཆེན་པོ་སྙིང་ཐིག་ཡ་བཞི་ལས་མཁའ་འགྲོ་ཡང་ཏིག་གི་ཆོས་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0E9B:
      image_group_id: I3CN5347
      title: ''
      total_pages: 620
      order: 1
      base_file: 0E9B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
